// Generated by https://quicktype.io
// Control + shift + P -->  Buscar: Paste JSON as code

export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
